### ISSUE TITLE
Hotspots inside symbol masters aren't exported

### ISSUE THREAD

**Issue by romannurik** [romannurik/Sketch-FlowExporter#1]
Can be reproduced by doing **File** > **New from Template** > **Prototyping Tutorial** in Sketch and exporting... the tab bar at the bottom isn't interactive in the exported prototype.

Should be easy-ish to fix at first glance..

**Comment by romannurik** [comment]
Re-opening. To support this correctly, we have to look at symbol overrides to decide on target artboard.

**Comment by Lanfei** [comment]
@romannurik , why we need to decide the target artboard according to symbol overrides? I think a target artboard in Sketch can only be a symbol master?

I tried in Sketch preview, the flow still linked to the symbol master even if I override something in a symbol instance.

**Comment by romannurik** [comment]
@Lanfei I don't recall the exact line of thinking but it's likely related to this situation:

1. Symbol has a nested symbol with hotspots
2. You instantiate that symbol and swap out the nested symbol (via an override) with a different one, with different hotspots

The result of that is that we need to use the override symbol's hotspots, not the original nested symbol in the symbol master.

**Comment by Lanfei** [comment]
@romannurik As I saw in the code [here](https://github.com/romannurik/Sketch-FlowExporter/blob/master/src/command-export-html.js#L201), it's not using the override symbol's hotspots, but changing the target of the hotspot, which is not done in Sketch preview.

Regarding the situation that we need to use the override symbol's hotspots, not the original nested symbol in the symbol master, it is already done by `.detachByReplacingWithGroup()` function.

I was asking because I solved a problem that [the hotspots in symbol instances covered hotspots in parent](https://lanfei.github.io/Sketch-FlowExporter/hotspot-cover-issue.html) and wanted to create a PR, but I [removed the mechanism about overrides](https://github.com/Lanfei/Sketch-FlowExporter/blob/master/src/command-export-html.js#L167).

**Comment by romannurik** [comment]
Hey @Lanfei,

So I took another look, and it's definitely still the case that to determine where a hotspot links to (the target artboard), you need to look at overrides. Just do **File > New from Template > Prototyping Tutorial** and check out how the bottom tab bar works. When selecting a symbol instance of the tab bar, Sketch gives you a UI to customize where each hotspot in the symbol master should point to (even allowing you to choose 'None' to disable the hotspot):

![image](https://user-images.githubusercontent.com/100155/50646327-c2fb8600-0f43-11e9-86b1-b29ecbfe46eb.png)

Please let me know if I'm misunderstanding, and sincerest apologies for the delay!
